# Generated by Django 3.2.9 on 2021-12-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
    ]
