# Generated by Django 3.2.9 on 2021-12-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='Images/default_image.img', upload_to='Images/'),
        ),
    ]
